### ISSUE TITLE
React form validation not rendered IE11 script errors

### ISSUE THREAD

**Issue by daileytj** [pxblue/react-design-patterns#20]
#### Bug or feature request?
Bug

#### What is the expected behavior?
component to load in IE

#### What is the current behavior?
component does not load

#### What are the steps to reproduce?
1. yarn start on react form-validation
2. Open http://localhost:3000/ in internet explorer

#### What is your environment?

 Framework
- [ ] Angular
- [X] React

 Browser
- [X] Internet Explorer
- [ ] Safari
- [ ] Chrome
- [ ] Firefox

 Operating System
- [ ] MacOS
- [X] Windows
- [ ] Other
		
#### Anything else to add?
SCRIPT1002: Syntax error
0.chunk.js (15522,34)
SCRIPT1002: Syntax error
main.chunk.js (56,34)

**Comment by huayunh** [comment]
IE11 will no longer be supported after May 2021; will need to make stories to update support for IE11.
