### ISSUE TITLE
Should run on IE 11

### ISSUE THREAD

**Issue by jeffvg** [pxblue/react-design-patterns#24]
#### Describe the bug
Nothing loads in IE 11 and promise is undefined 

#### What is the expected behavior?
patterns and app to work with IE

#### What are the steps to reproduce?
1. run repo
2. open in IE

#### Environment

Windows
IE 11

**Comment by emclaug2** [comment]
PXB CLI should generate projects that work with ie11.  This was generated with the cli & should work.

**Comment by huayunh** [comment]
IE11 will no longer be supported after May 2021; will need to make stories to update support for IE11.
