### ISSUE TITLE
Forms don't adhere to spacing specs

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-design-patterns#44]
#### Describe the bug
The spacing between form fields is 16px.

#### What is the expected behavior?
Should be 32px between fields on desktop size according to our specs.

#### What are the steps to reproduce?
1. Open the forms example on code sandbox
2. Observe the spacing between form elements.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/95351645-71f29180-088f-11eb-9906-7c0448154d0d.png)
		
#### Anything else to add?
Do we want to update our spec to include options for 'dense' forms with lots of fields to allow 16px as an acceptable alternative?

**Comment by huayunh** [comment]
TODO: Check ng too

**Comment by joebochill** [comment]
Angular appears to be correct already.
