### ISSUE TITLE
Use Refs for Form Focus & Select

### ISSUE THREAD

**Issue by emclaug2** [pxblue/react-design-patterns#86]
#### Describe the desired behavior
In the Form Validation examples, use React Refs instead of document & DOM to focus input fields.

#### Describe the current behavior
It's currently using javascript.

#### Is this request related to a current issue?
No

#### Additional Context
React Design Pattern Form Validation Examples

**Comment by jeffvg** [comment]
not high priority but if the solution to enhance is a quick win go for it
